from tomcat:8.5-jdk8

WORKDIR C:\xampp\tomcat\webapps
COPY C:\xampp\tomcat\webapps\javaParcial PRUEBA SERVIDOR
COPY C:\xampp\tomcat\webapps\javaParcial PRUEBA SERVIDOR\WEB-INF\lib\
COPY C:\xampp\tomcat\webapps\javaParcial PRUEBA SERVIDOR\img

EXPOSE 8080

CMD["catalina.sh", "run"]

